- hosts: target
  roles:
    - ansible

- hosts: target
  vars:
    workdir: ~/wks/playbooks
  tasks:
    - file:
        path: "{{ workdir }}"
        state: directory
    - git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop:
        - repo: https://github.com/tateishi/playbook-work.git
          dest: "{{ workdir }}/playbook-work"
