- name:  basic configurations
  hosts: target
  roles:
    - name: set timezone
      role: timezone
    - name: apt update && apt upgrade -y
      role: apt-upgrade
    - name: install packages
      role: packages
    - name: check out dotfiles
      role: dotfiles-chezmoi
    - name: install source highlight
      role: source-highlight
